services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"  # Expose Nginx on host port 8080
    volumes:
      - ./src/public:/var/www/public  # Mount project files
      - ./src/front-end:/var/www/front-end
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use custom Nginx config
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./src/public:/var/www/public
      - ./src/routes:/var/www/routes
      - ./src/front-end:/var/www/front-end
      - ./src/back-end:/var/www/back-end
