services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"  # Expose Nginx on host port 8080
     #- "8081:443"  # Expose Nginx on host port 8080

    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf  # Use custom Nginx config
        #- ./ssl:/var/www/html/ssl
    depends_on:
      - php
    networks:
     - my_network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks:
     - my_network

networks:
  my_network:
