services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"  # Expose Nginx on host port 8080
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf  # Use custom Nginx config
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
