USE 4592700_fursure;

CREATE TABLE IF NOT EXISTS Users (
    Users_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description TEXT NULL,
    Phone VARCHAR(20) NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Admin BOOLEAN NOT NULL DEFAULT FALSE,
    Banned BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS Business (
    Business_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description TEXT NULL,
    Phone VARCHAR(20) NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Service (
    Service_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description TEXT NULL,
    Business_ID INT NOT NULL,
    Image BLOB NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Label JSON NOT NULL,
    FOREIGN KEY (Business_ID) REFERENCES Business(Business_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Verification (
    Service_ID INT NOT NULL,
    Users_ID INT NOT NULL,
    PRIMARY KEY (Service_ID, Users_ID),
    FOREIGN KEY (Service_ID) REFERENCES Service(Service_ID) ON DELETE CASCADE,
    FOREIGN KEY (Users_ID) REFERENCES Users(Users_ID) ON DELETE CASCADE,
    UNIQUE(Service_ID, Users_ID)
);

CREATE TABLE IF NOT EXISTS Advertisement (
    Ad_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description TEXT NULL,
    Business_ID INT NOT NULL,
    Label JSON NOT NULL,
    FOREIGN KEY (Business_ID) REFERENCES Business(Business_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Messages (
    Message_ID INT AUTO_INCREMENT PRIMARY KEY,
    Receiver_ID INT NOT NULL,
    Sender_ID INT NOT NULL,
    Message TEXT NOT NULL,
    Timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Banned BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (Receiver_ID) REFERENCES Users(Users_ID) ON DELETE CASCADE,
    FOREIGN KEY (Sender_ID) REFERENCES Users(Users_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Review (
    Review_ID INT AUTO_INCREMENT PRIMARY KEY,
    Comment TEXT NULL,
    Stars DECIMAL(2,1) NOT NULL CHECK (Stars BETWEEN 1 AND 5 AND Stars * 2 = FLOOR(Stars * 2)),
    Users_ID INT NOT NULL,
    Service_ID INT NOT NULL,
    Banned BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (Users_ID) REFERENCES Users(Users_ID) ON DELETE CASCADE,
    FOREIGN KEY (Service_ID) REFERENCES Service(Service_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Labels (
    Label_ID INT AUTO_INCREMENT PRIMARY KEY,
    Description VARCHAR(255) NOT NULL
);